version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etimen-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=https://bsr41lqbdqxe9imp133h0isl.152.53.151.102.sslip.io
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_APP_NAME=Etimen
      - NEXT_PUBLIC_APP_URL=https://bsr41lqbdqxe9imp133h0isl.152.53.151.102.sslip.io
    networks:
      - coolify
      - etimen-network

networks:
  coolify:
    external: true
  etimen-network:
    driver: bridge
